"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"
ui-default-command = "log"

[user]
name = "Tommy McCormick"
email = "mccormickt9@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDCoSWtk4fb/3z5j7wvMt+A9kpCCWlaPm9Y9j64RlvYA"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[ui]
editor = "nvim"

[git]
auto-local-bookmark = true
sign-on-push = true
write-change-id-header = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]

# Set email to work email when in work directory
[[--scope]]
--when.repositories = ["~/adversarial"]
[--scope.user]
email = "tommy@adversarial.com"

# disable pagination for `jj status`, use `delta` for `jj diff` and `jj show`
[[--scope]]
--when.commands = ["status"]
[--scope.ui]
paginate = "never"
[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
